-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  user_id uuid,
  campaign_id uuid,
  lead_id uuid,
  account_id uuid,
  activity_type character varying NOT NULL,
  status character varying DEFAULT 'completed'::character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activities_pkey PRIMARY KEY (id),
  CONSTRAINT activities_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT activities_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT activities_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT activities_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.connected_accounts(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  user_id uuid,
  action character varying NOT NULL,
  entity_type character varying NOT NULL,
  entity_id uuid NOT NULL,
  previous_state jsonb,
  new_state jsonb,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.campaign_executions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid,
  lead_id uuid,
  workflow_execution_id text,
  status character varying DEFAULT 'pending'::character varying,
  current_step integer DEFAULT 0,
  total_steps integer NOT NULL,
  execution_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT campaign_executions_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_executions_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT campaign_executions_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  creator_id uuid,
  name text NOT NULL,
  description text,
  status character varying DEFAULT 'draft'::character varying,
  lead_list_id uuid,
  account_id uuid,
  workflow_id text,
  workflow_definition jsonb NOT NULL,
  schedule jsonb NOT NULL,
  stats jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT campaigns_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.users(id),
  CONSTRAINT campaigns_lead_list_id_fkey FOREIGN KEY (lead_list_id) REFERENCES public.lead_lists(id),
  CONSTRAINT campaigns_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.connected_accounts(id)
);
CREATE TABLE public.connected_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  organization_id uuid,
  provider character varying NOT NULL,
  provider_account_id text NOT NULL,
  display_name text NOT NULL,
  email text,
  profile_picture_url text,
  status character varying DEFAULT 'connected'::character varying,
  capabilities jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  last_synced_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT connected_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT connected_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT connected_accounts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.lead_lists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  creator_id uuid,
  name text NOT NULL,
  description text,
  source character varying NOT NULL,
  total_leads integer DEFAULT 0 CHECK (total_leads >= 0),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying, 'archived'::character varying]::text[])),
  processed_leads integer DEFAULT 0 CHECK (processed_leads >= 0),
  failed_leads integer DEFAULT 0 CHECK (failed_leads >= 0),
  original_filename text,
  csv_file_url text,
  sample_csv_url text,
  file_size bigint CHECK (file_size >= 0),
  processing_started_at timestamp with time zone,
  processing_completed_at timestamp with time zone,
  error_message text,
  tags ARRAY DEFAULT '{}'::text[],
  filters jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  stats jsonb DEFAULT '{}'::jsonb,
  connected_account_id uuid NOT NULL,
  CONSTRAINT lead_lists_pkey PRIMARY KEY (id),
  CONSTRAINT lead_lists_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT lead_lists_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.users(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_list_id uuid,
  full_name text NOT NULL,
  first_name text,
  last_name text,
  email text,
  phone text,
  title text,
  company text,
  industry text,
  location text,
  linkedin_url text,
  linkedin_id text,
  status character varying DEFAULT 'new'::character varying,
  source character varying NOT NULL,
  enrichment_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_lead_list_id_fkey FOREIGN KEY (lead_list_id) REFERENCES public.lead_lists(id)
);
CREATE TABLE public.organization_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  user_id uuid,
  role character varying DEFAULT 'member'::character varying,
  permissions jsonb DEFAULT '{}'::jsonb,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_members_pkey PRIMARY KEY (id),
  CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE,
  logo_url text,
  website_url text,
  plan character varying DEFAULT 'free'::character varying,
  billing_email text,
  subscription_status character varying DEFAULT 'active'::character varying,
  monthly_campaign_limit integer DEFAULT 5,
  monthly_lead_limit integer DEFAULT 1000,
  user_limit integer DEFAULT 5,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by_auth_id uuid,
  external_id text UNIQUE,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_created_by_auth_id_fkey FOREIGN KEY (created_by_auth_id) REFERENCES auth.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  external_id text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  auth_user_id uuid,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);